name: contexts-example

on:
  push:
  pull_request:

jobs:
  use-contexts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        greeting: [Hello, Howdy, Hey]

    steps:
      - uses: actions/checkout@v2
      - name: Print greeting
        run: echo ${{ matrix.greeting }}
        env:
          GREETING: ${{ matrix.greeting }}

      - name: Do work with a secret
        run: ./workRequiringASecret.sh
        env:
          A_SECRET: ${{ secrets.USERNAME }}

      - name: Run only for pulls
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "Triggered by a pull request"
